### ISSUE TITLE
about the train_kitti_desc.sh

### ISSUE THREAD

**Issue by liaojinli** [ispc-lab/HRegNet#1]
What is the input of --pretrain_detector PRETRAIN_DETECTOR in train_kitti_desc.sh?

**Comment by FanLu97** [comment]
@liaojinli Noting that the feature extraction module should be trained in two stages, i.e., train detector first and then train descriptor. The PRETRAIN_DETECTOR should be the pre-trained weights in the first stage (using scripts/train_kitti_det.sh). We will upload the pre-trained weights of the feature extractor module in a few days for better reproducibility (maybe after one/two weeks).

**Comment by liaojinli** [comment]
@FanLu97 Thank you very much for your answer.

**Comment by FanLu97** [comment]
@liaojinli Thanks for your patience! Pretrained weights of the feature extractor module are updated in ckpt/pretrained. You can check README for more details.
