### ISSUE TITLE
Test Keypoints

### ISSUE THREAD

**Issue by fatemechangizian** [ispc-lab/HRegNet#11]
Hello, 
I am trying to use just the keypoint detector part and am willing to use the pretrained detector weights to be tested on my own data sample (save keypoints of each pointcloud). I can see that there is a test.py for the testing entire network, could you please guide me on how can I test just the detector part and not the entire Net on my sample?

Thanks for the nice work, btw.
Looking forward to your response.
Fatemeh

**Comment by FanLu97** [comment]
@fatemechangizian Hello, thanks for your interests.
We provide pretrained weights of detector network ('{dataset}_keypoints.pth') and the whole feature extraction module ('{dataset}_desc.pth') in ckpt/pretrained. You can load the weights to the module HierFeatureExtraction (models/models.py) for simple feature extraction.

**Comment by FanLu97** [comment]
Long time no updates. Closed.
