### ISSUE TITLE
Apply to frame-submap

### ISSUE THREAD

**Issue by nuo-1** [ispc-lab/HRegNet#13]
Hello, great work done in this model! I want to ask if this model can be applied to single-frame pair of sub-maps. If the application is in the loop closure scenario, it feels better to use submap.

**Comment by FanLu97** [comment]
Hello,
do you mean registering two sub-maps or registering a frame of point cloud to a sub-map?

**Comment by nuo-1** [comment]
> Hello, do you mean registering two sub-maps or registering a frame of point cloud to a sub-map?

Of course, both methods can be used. At present, I want to register a frame of point cloud to a sub-map. Can you give me some suggestions on the network and implementation? 
Thanks!

**Comment by FanLu97** [comment]
Hello,
I suggest you can first transform the point cloud and submap to a relatively close spatial coordinate, and crop the submap to keep the overlap with the current point cloud.

**Comment by nuo-1** [comment]
> Hello, I suggest you can first transform the point cloud and submap to a relatively close spatial coordinate, and crop the submap to keep the overlap with the current point cloud.

Okay, thanks, I'll try.
