### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by CCCCe** [ispc-lab/HRegNet#15]
Sorry, I can't run 'sh scripts/...',  I download dataset from kitty ,but it doesn't run in my computer.  I hava  two questions for this problem: 1. the resource of dataset is right? 2.how to  build construction(file) with dataset?

**Comment by yn10828** [comment]
I have the same problem as you, please answer

**Comment by FanLu97** [comment]
Hello,
I think the data resource should be right. Please confirm the organization of the dataset is the same as the statement in the README.
