### ISSUE TITLE
how to build nuscene dataset in project

### ISSUE THREAD

**Issue by CCCCe** [ispc-lab/HRegNet#16]
Hello,Great work done on this model. I am reproducing in my own environment, but I have some questions when building the nuscene data set, because there are many types of sensors, so I should download all the data from individual sensors.

[https://www.nuscenes.org/download](url)

**Comment by FanLu97** [comment]
Hello,
you can only download the Lidar blobs and the Metadata.

**Comment by CCCCe** [comment]
> Hello, you can only download the Lidar blobs and the Metadata.

Are you  mean "nuscenes-lidarseg"，right？

**Comment by FanLu97** [comment]
It should be the Full dataset (v1.0) (not nuScenes-lidarseg), and only the Lidar blobs (maybe also the keyframe blobs) and the metadata should be downloaded.

**Comment by CCCCe** [comment]
> It should be the Full dataset (v1.0) (not nuScenes-lidarseg), and only the Lidar blobs (maybe also the keyframe blobs) and the metadata should be downloaded.

Sorry,I downloaded FULL dateset (V1.0), but the content of the file is not your dataset structure as README, can you please explain in detail

**Comment by CCCCe** [comment]
> It should be the Full dataset (v1.0) (not nuScenes-lidarseg), and only the Lidar blobs (maybe also the keyframe blobs) and the metadata should be downloaded.

I mean that  all file blobs are used in your project? and sweep file needn't any data?

**Comment by FanLu97** [comment]
Yes, we use file blobs of all scenes. We do not need sweep files due to that we use point cloud of keyframes (2Hz).

**Comment by CCCCe** [comment]
> Yes, we use file blobs of all scenes. We do not need sweep files due to that we use point cloud of keyframes (2Hz).

Thanks a lot.   And I didn't find visualization file under the project. Are you achieving in other project?
