### ISSUE TITLE
Bug in Hierarchical Transformation

### ISSUE THREAD

**Issue by WinterCodeForEverything** [ispc-lab/HRegNet#3]
I think there's a mistake in Hierarchical Transformation from coarse to fine, the last element in transformation matrix should be 1 not 0, it will result the wrong translation. Maybe it can be fixed like this:
![image](https://user-images.githubusercontent.com/28380063/144383291-b98028d8-6052-40e0-a45c-71ee9901c606.png)

**Comment by FanLu97** [comment]
Hi, @WinterCodeForEverything 
Thanks for pointing out this bug! We have updated the code. Besides, we have observed a performance improvement by fixing this bug. We will update the pre-train models in a few days.
Thanks again!

**Comment by WinterCodeForEverything** [comment]
I'm confused that I get a even worse performance after fixing the bug, especially the translation error, would you please offer pre-train models to prove it has better performance?

**Comment by FanLu97** [comment]
We have updated the pre-trained models and the code. Maybe you can clone the new version for testing.

**Comment by WinterCodeForEverything** [comment]
Ok, thanks.

**Comment by FanLu97** [comment]
Please let me know if you have any new updates, thanks.

**Comment by WinterCodeForEverything** [comment]
Haha, sure.
