### ISSUE TITLE
How to get the rotation error?

### ISSUE THREAD

**Issue by xiyue-wx** [ispc-lab/HRegNet#4]
Thank for your generous sharing.
However after I reproduced your experiment, I found that the results of the rotation error in the KITTI_SUMMARY is not consistent with the results in the paper. How did you get it from the results in the KITTI_SUMMARY?

**Comment by FanLu97** [comment]
Hello, @xiyue-wx ,
Thanks for your interest in our work. The Rotation mean and Rotation std is the rotation error in the paper, it should be consistent with the paper. Could you please provide the reproduced results in your "kitti_summary" file?

**Comment by xiyue-wx** [comment]
The results in the summary are as follows：
Dataset: kitti
Translation threshold: 2.00
Rotation threshold: 5.00
Translation mean: 0.1237
Translation std: 0.1342
Rotation mean: 0.9911
Rotation std: 1.0370
Runtime: 107276.5362
Success rate: 0.9965

**Comment by FanLu97** [comment]
It's weird. It seems that the translation error and success rate are consistent with my results. I will re-run the code and put the results here. Besides, I have updated the code today and maybe you can download the new version and re-run the experiments.

**Comment by xiyue-wx** [comment]
thanks, I will download the updated code and re-sun the experiments

**Comment by FanLu97** [comment]
I re-run the experiments with the current version and the results on KITTI dataset are listed below, which is slightly better than the version in the paper. 
Dataset: kitti
Translation threshold: 2.00
Rotation threshold: 5.00
Translation mean: 0.1106
Translation std: 0.1123
Rotation mean: 0.2807
Rotation std: 0.2380
Runtime: 111652.4726
Success rate: 0.9971
Please let me know if you have any new results, thanks.

**Comment by xiyue-wx** [comment]
I re-run the updated experiments, it's weirder.
Dataset: kitti
Translation threshold: 2.00
Rotation threshold: 5.00
Translation mean: 0.0539
Translation std: 0.0699
Rotation mean: 0.9203
Rotation std: 1.0351
Runtime: 118950.0126
Success rate: 0.9988

**Comment by FanLu97** [comment]
It's weird. Maybe you can e-mail me your contact information for more convenient communications. My email: lufan@tongji.edu.cn

**Comment by FanLu97** [comment]
Close due to inactivity.

**Comment by jiangchaokang** [comment]
> I re-run the updated experiments, it's weirder. Dataset: kitti Translation threshold: 2.00 Rotation threshold: 5.00 Translation mean: 0.0539 Translation std: 0.0699 Rotation mean: 0.9203 Rotation std: 1.0351 Runtime: 118950.0126 Success rate: 0.9988

I'm having the same problem as you. Have you solved this issue? I would like to know what the solution is? Looking forward to your reply！
