### ISSUE TITLE
Question in CoarseReg class

### ISSUE THREAD

**Issue by sYANGunique1111** [ispc-lab/HRegNet#6]
Hello,

Thank you for your generosity to share the code. However I got stuck when I come to the forward() function of CoarseReg class.

<img width="362" alt="屏幕截图 2022-01-27 111733" src="https://user-images.githubusercontent.com/74031170/151285928-337fa380-1b3d-475c-aff9-524ed46e2b18.png">

What I understand about line 249 and line 255 is that you want to gather k nearest cosine neighbors in src for keypoints in dst and k nearest neighbors in dst for keypoints in src. I didn't understand why you used **src_knn_idx**  for both cases? I assume it should be **dst_knn_idx**  instead in line 249,  because it gathers k nearest neighbors in src to keypoints in dst.

Best regards.

**Comment by FanLu97** [comment]
Hello,
This operation does not aim to gather k nearest cosine neighbors in src for keypoints in dst and k nearest neighbors in dst for keypoints in src. We only search k nearest neighbors in dst for each keypoint in src, and this operation aims to obtain the bilateral similarity of the candidate corresponding points (from src_dst_cos_norm and dst_src_cos_norm).

**Comment by sYANGunique1111** [comment]
Hello,
I understand, thank you for the answer

**Comment by FanLu97** [comment]
Resolved, close.
