### ISSUE TITLE
"import point_utils_cuda" cant make it

### ISSUE THREAD

**Issue by Git-oNmE** [ispc-lab/HRegNet#8]
I was running `sh scripts/train_kitti_det.sh`,then I got the error message

```
/home/hlf/miniconda3/envs/HRegNet/lib/python3.9/site-packages/MinkowskiEngine-0.5.4-py3.9-linux-x86_64.egg/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
Traceback (most recent call last):
  File "/media/data3/hlf_data/HRegNet0/HRegNet/train_feats.py", line 7, in <module>
    from data.kitti_data import KittiDataset
  File "/media/data3/hlf_data/HRegNet0/HRegNet/data/kitti_data.py", line 11, in <module>
    from models.utils import generate_rand_rotm, generate_rand_trans, apply_transform
  File "/media/data3/hlf_data/HRegNet0/HRegNet/models/utils.py", line 7, in <module>
    import point_utils_cuda
ImportError: /home/hlf/miniconda3/envs/HRegNet/lib/python3.9/site-packages/point_utils-0.0.0-py3.9-linux-x86_64.egg/point_utils_cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20getCurrentCUDAStreamEa
```

I checked my file list, found no file named "point_utils_cuda.py" indeed. 
![image](https://user-images.githubusercontent.com/29742421/168082102-66586d2a-da50-4386-a8fc-ff78c5505523.png)

How can I deal with this problem? Thank you very much!

**Comment by FanLu97** [comment]
Hello, It seems like the version of pytorch or cuda does not match. We only test the code with cuda11.0/11.0 and torch 1.7.0/1.7.1.

**Comment by Git-oNmE** [comment]
> Hello, It seems like the version of pytorch or cuda does not match. We only test the code with cuda11.0/11.0 and torch 1.7.0/1.7.1.

Thank you for your quick reply, firstly.
My server's CUDA version is 11.1, which I can't change. And my torch version is 1.7.1. 
Like it said in the requirement section, maybe torch 1.7.1 with CUDA 11.1 should be ok?
![image](https://user-images.githubusercontent.com/29742421/168217909-7fa253ea-70db-468c-9dbc-c8e933024532.png)

**Comment by FanLu97** [comment]
Yes, cuda 11.1 with torch 1.7.1 should be OK (this is the environment I am using now). I'm sorry I don't know how to solve this problem. I have run the code on multiple platforms and have not encountered your problem.

**Comment by Git-oNmE** [comment]
> Yes, cuda 11.1 with torch 1.7.1 should be OK (this is the environment I am using now). I'm sorry I don't know how to solve this problem. I have run the code on multiple platforms and have not encountered your problem.

I deleted all files and installed again, and this problem disappeared! :)

But now I come into another problem about the dataset, I submitted it in another issue, could you please take a look? Thanks!
